apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: gpu-test
    zarf.dev/agent: ignore
  name: gpu-test
---
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
  namespace: gpu-test
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      image: "ghcr.io/runyontr/packages/cuda-vector-add:v0.1"
      resources:
        limits:
          nvidia.com/gpu: 1
